### ISSUE TITLE
Submit Jonah profile to the people file

### ISSUE THREAD

**Issue by js336rice** [dossgollin-lab/dossgollin-lab.github.io#84]
Going to submit my own profile to the people file

**Comment by js336rice** [comment]
![Jonah](https://github.com/dossgollin-lab/dossgollin-lab.github.io/assets/156249455/7db18e87-059e-41ae-95a4-93d354a957b7)

**Comment by jdossgollin** [comment]
Can you crop the photo to square? Will work better as a circle

**Comment by js336rice** [comment]
Can do.  Also, I was going to email you to ask about uploading the .qmd
file to the issue, GitHub is saying that it doesn’t support that file type?


I also tried uploading directly to the folder that the other profiles are
in, but got a message that I didn’t have the necessary permissions to do
that

**Comment by js336rice** [comment]
![Jonah](https://github.com/dossgollin-lab/dossgollin-lab.github.io/assets/156249455/3d78fd62-e278-46db-9ed4-8c4cc597bd19)

**Comment by js336rice** [comment]
---
title: "Jonah Schaechter"
sortby: "Schaechter, Jonah"
position: "Ph.D. Student"
started: "Spring 2024"
ended: "Current"
toc: false
about:
    id: person-profile
    image: "../../_assets/img/people/Jonah.jpg"
    template: trestles
    links:
        -   icon: github
            text: Github
            href: https://github.com/js336rice
        -   icon: linkedin
            text: LinkedIN
            href: https://www.linkedin.com/in/jonah-schaechter/
        -   icon: envelope
            text: Email
            href: mailto:js336@rice.edu

format: 
  html:
    page-layout: full
---

:::{#person-profile}
## Bio

Jonah Schaechter is a Ph.D. student in the Civil and Environmental Engineering department at Rice University.
Jonah completed a BS and MS at Columbia University in Mechanical Engineering.  He is interested in climate damage mitigation, and how we adapt infrastructure both to reduce emissions, and to be more resiliant to climate change.

## Education
- **Columbia University** | New York, NY, USA<br />MS in Mechanical Engineering Engineering, 2022
<br />BS in Mechanical Engineering Engineering, 2021

:::

**Comment by js336rice** [comment]
^Copied and pasted the text of the .qmd for now so at least I have a backup of that saved here

**Comment by jdossgollin** [comment]
Thanks @js336rice, this is definitely all the information needed. However, if you want the full pull request experience what you'll need to do is the following. Let me know if it's helpful compared to what's  the README and I'll update it there

1. Clone the repository to your machine
    1. Fork the repository on GitHub. *You do not have the ability to edit `dossgollin-lab/dossgollin-lab.github.io`. This will create `<your_username>/dossgollin-lab.github.io` that you can edit.
    2. Clone your forked repository (`<your_username>/dossgollin-lab.github.io`) to your computer (the easiest way to do this is using GitHub desktop, but there are many ways).
    3. This repository has some submodules. Don't worry if you don't know what that is. In a terminal window (open to the folder you just cloned) run `git submodule update --init --recursive` to get submodules up and running
2. Make any changes to the site. Here are some common ones:
    1. To add yourself to the [People](https://dossgollin-lab.github.io/people/) page:
        1. Add a **square** picture of yourself to `_assets/img/people`
        2. Add a file to the appropriate sub-folder in `people/`. Modify it to include your own information. It is suggested to start from the page of someone else and then customize it to include your own information.
3. Preview the site (optional but recommended!): there are two ways
    1. Docker installation option (runs slow but less can go wrong):
        1. You'll need Docker Desktop
        3. In a terminal window open to this repository, run `make install`. This will use 
Docker to install the packages you need.
        4. To preview the website, run `make devserver`
    3. Native Ruby installation (runs faster but can be a bit tricky to install properly):
        1. In a terminal window open to this repository, run `bundle install` to install required packages. If you don't have bundle set up, you will need to install it.
        2. If you chose the native Ruby installation option above, run `bundle exec jekyll serve -w`
4. Push your changes back to the website.
    1. Stage and commit your changes (again, GitHub Desktop is recommended for beginners)
    2. Push changes (they will go to your fork of the repository on GitHub)
    3. Create a Pull Request to update the full website. *This is a way for the changes you make on your own fork of the project to be merged in to the shared repository*.

**Comment by js336rice** [comment]
Saw this earlier this week, working on it now.  I appreciate the in-depth instructions!

**Comment by js336rice** [comment]
Created pull request!
